### ISSUE TITLE
Find Hero image

### ISSUE THREAD

**Issue by anthonyhi11** [codefordallas/codefordallas.github.io#12]
Assigned to everyone because we want a pool of images to choose from :)

**Comment by Sukanyarits** [comment]
![cropped-dallas-skyline-background](https://user-images.githubusercontent.com/54338670/89241359-45d33f80-d5c4-11ea-8591-5cdf7108d7f3.jpg)
![dallas-droneview](https://user-images.githubusercontent.com/54338670/89241360-45d33f80-d5c4-11ea-9103-e2bccdd4657e.jpg)
![dallas-skyline-bright-1024x688](https://user-images.githubusercontent.com/54338670/89241361-466bd600-d5c4-11ea-9c43-08c980736802.jpg)
![Dallas_smaller1](https://user-images.githubusercontent.com/54338670/89241363-47046c80-d5c4-11ea-8d5b-0d0f46bb39ad.jpg)
![Dallas-Skyline-1080x675](https://user-images.githubusercontent.com/54338670/89241365-479d0300-d5c4-11ea-8b50-97f195c863e2.png)
![Dallas_CVB_Clay_Coleman_2](https://user-images.githubusercontent.com/54338670/89241367-479d0300-d5c4-11ea-9ec5-e127dd17947e.jpg)
![dallasm-multicolor](https://user-images.githubusercontent.com/54338670/89241369-48359980-d5c4-11ea-8b61-718eb1c105a6.jpeg)
![Blue-Mono-Dallas-Skyline](https://user-images.githubusercontent.com/54338670/89241370-48359980-d5c4-11ea-9076-cf52efcde5af.png)
